const products=[
{id:1,cat:'mobile',name:'Smartphone X Pro',type:'Smartphone',price:799,bs:'309.240 Bs',badge:'Bestseller',img:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=85',rating:'4.9',specs:['6.7" OLED 120 Hz','256 GB · 12 GB RAM','Cámara Pro 50 MP','Garantía 12 meses'],desc:'Un flagship equilibrado para productividad, fotografía y entretenimiento, con una experiencia premium de principio a fin.'},
{id:2,cat:'audio',name:'AirSound Max',type:'Audífonos',price:249,bs:'96.366 Bs',badge:'Nuevo',img:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',rating:'4.8',specs:['Cancelación activa','40 h de batería','Bluetooth 5.4','Carga USB-C'],desc:'Audio inmersivo, comodidad para todo el día y control inteligente para tus desplazamientos.'},
{id:3,cat:'computing',name:'UltraBook 14',type:'Laptop',price:1099,bs:'425.214 Bs',badge:'Top',img:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=85',rating:'4.9',specs:['14" 2.8K','Intel Core Ultra 7','16 GB · 1 TB SSD','Batería 14 h'],desc:'Una laptop ligera con rendimiento serio para diseño, negocio y creación de contenido.'},
{id:4,cat:'mobile',name:'SmartWatch S2',type:'Wearable',price:329,bs:'127.326 Bs',badge:'-15%',img:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=85',rating:'4.7',specs:['AMOLED 1.9"','GPS integrado','7 días de batería','Resistencia 5 ATM'],desc:'Métricas, notificaciones y estilo en una pieza diseñada para acompañarte todo el día.'},
{id:5,cat:'audio',name:'Studio Buds',type:'Audio',price:159,bs:'61.524 Bs',badge:'Nuevo',img:'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=85',rating:'4.8',specs:['ANC híbrido','36 h total','Modo transparencia','Carga rápida'],desc:'Unos earbuds compactos con sonido potente y autonomía suficiente para toda la jornada.'},
{id:6,cat:'computing',name:'Mechanical 75',type:'Teclado',price:119,bs:'46.086 Bs',badge:'Top',img:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=85',rating:'4.9',specs:['75% layout','Hot-swap','RGB por tecla','Switches lineales'],desc:'Compacto, preciso y personalizable para gaming y productividad.'},
{id:7,cat:'mobile',name:'Tablet Air 11',type:'Tablet',price:579,bs:'224.082 Bs',badge:'-10%',img:'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=900&q=85',rating:'4.8',specs:['11" Liquid display','128 GB','Wi-Fi 6E','USB-C'],desc:'Pantalla amplia y portátil para consumir, crear y trabajar desde cualquier lugar.'},
{id:8,cat:'computing',name:'Pro Monitor 27',type:'Monitor',price:399,bs:'154.812 Bs',badge:'Oferta',img:'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=85',rating:'4.7',specs:['27" 4K','144 Hz','USB-C 90W','HDR'],desc:'Espacio visual profesional para diseño, edición y multitarea.'}
];
const saved=JSON.parse(localStorage.getItem('techla-state')||'{}');
const state={filter:'all',cart:Array.isArray(saved.cart)?saved.cart:[],wish:Array.isArray(saved.wish)?saved.wish:[],compare:Array.isArray(saved.compare)?saved.compare:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>`$${Number(n).toLocaleString('en-US')}`;
function persist(){localStorage.setItem('techla-state',JSON.stringify(state))} function getProduct(id){return products.find(p=>p.id===Number(id))}
function toast(text){const el=$('#toast');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)}
function toggleWish(id){id=Number(id);state.wish=state.wish.includes(id)?state.wish.filter(x=>x!==id):[...state.wish,id];persist();renderProducts();toast(state.wish.includes(id)?'Guardado en tu wishlist':'Quitado de tu wishlist')}
function toggleCompare(id){id=Number(id);if(state.compare.includes(id))state.compare=state.compare.filter(x=>x!==id);else if(state.compare.length<3)state.compare=[...state.compare,id];else return toast('Puedes comparar hasta 3 productos');persist();updateCompareBar();renderProducts()}
function renderProducts(){const grid=$('#product-grid');if(!grid)return;const list=state.filter==='all'?products:products.filter(p=>p.cat===state.filter);grid.innerHTML=list.map(p=>`<article class="product-card reveal visible" data-id="${p.id}"><div class="product-media"><span class="badge">${p.badge}</span><div class="product-tools"><button class="tool-btn ${state.wish.includes(p.id)?'active':''}" data-wish="${p.id}" aria-label="Wishlist">♡</button><button class="tool-btn ${state.compare.includes(p.id)?'active':''}" data-compare="${p.id}" aria-label="Comparar">⇄</button></div><img src="${p.img}" alt="${p.name}" loading="lazy"><button class="quick-add" data-add="${p.id}" aria-label="Agregar ${p.name}">+</button></div><div class="product-meta"><small>${p.type} · ★ ${p.rating}</small><h3><a class="product-link" href="producto.html?id=${p.id}">${p.name}</a></h3><div class="price-row"><strong>${money(p.price)}</strong><span>${p.bs}</span></div></div></article>`).join('');$$('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();addToCart(b.dataset.add)});$$('[data-wish]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleWish(b.dataset.wish)});$$('[data-compare]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleCompare(b.dataset.compare)})}
function addToCart(id){const p=getProduct(id);if(!p)return;const line=state.cart.find(x=>x.id===p.id);if(line)line.qty+=1;else state.cart.push({id:p.id,qty:1});persist();updateCart();toast(`${p.name} agregado al carrito`)}
function changeQty(id,delta){const line=state.cart.find(x=>x.id===Number(id));if(!line)return;line.qty+=delta;if(line.qty<=0)state.cart=state.cart.filter(x=>x.id!==Number(id));persist();updateCart();updateSummary()}
function cartTotal(){return state.cart.reduce((sum,line)=>{const p=getProduct(line.id);return sum+(p?p.price*line.qty:0)},0)}
function updateCart(){const count=state.cart.reduce((s,x)=>s+x.qty,0);const countEl=$('.cart-count');if(countEl)countEl.textContent=count;const box=$('#cart-items');if(!box)return;if(!state.cart.length){box.innerHTML='<div class="empty-cart">Tu carrito está vacío.<br><br>Añade un producto para comenzar.</div>'}else box.innerHTML=state.cart.map(line=>{const p=getProduct(line.id);return `<div class="cart-line"><img src="${p.img}" alt="${p.name}"><div><b>${p.name}</b><span>${money(p.price)} · ${p.bs}</span><div class="cart-controls"><button class="qty-btn" data-minus="${p.id}">−</button><small>${line.qty}</small><button class="qty-btn" data-plus="${p.id}">+</button></div></div><strong>${money(p.price*line.qty)}</strong></div>`}).join('');$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));$('#cart-total').textContent=money(cartTotal())}
function updateSummary(){const box=$('#summary-items'),total=$('#summary-total');if(!box||!total)return;if(!state.cart.length)box.innerHTML='<div class="summary-item"><span>Sin productos</span><b>$0</b></div>';else box.innerHTML=state.cart.map(x=>{const p=getProduct(x.id);return `<div class="summary-item"><span>${p.name} × ${x.qty}</span><b>${money(p.price*x.qty)}</b></div>`}).join('');total.textContent=money(cartTotal())}
function openCart(){$('#cart-drawer').setAttribute('aria-hidden','false');$('#drawer-overlay').classList.add('on')};function closeCart(){$('#cart-drawer').setAttribute('aria-hidden','true');$('#drawer-overlay').classList.remove('on')}
function openCheckout(){if(!state.cart.length)return toast('Tu carrito está vacío');closeCart();updateSummary();$('#payment').setAttribute('aria-hidden','false')};function closeCheckout(){$('#payment').setAttribute('aria-hidden','true')}
function openSearch(){$('#search-modal').setAttribute('aria-hidden','false');setTimeout(()=>$('#search-input').focus(),100)};function closeSearch(){$('#search-modal').setAttribute('aria-hidden','true')}
function runSearch(term){const q=term.trim().toLowerCase();const hits=q?products.filter(p=>`${p.name} ${p.type} ${p.cat}`.toLowerCase().includes(q)).slice(0,6):[];$('#search-results').innerHTML=hits.length?hits.map(p=>`<a class="search-result" href="producto.html?id=${p.id}"><img src="${p.img}" alt=""><div><b>${p.name}</b><span>${p.type} · ★ ${p.rating}</span></div><strong>${money(p.price)}</strong></a>`).join(''):'<div class="empty-cart">Escribe un producto para empezar.</div>'}
function openProductModal(id){const p=getProduct(id);if(!p)return;$('#product-detail').innerHTML=`<div class="product-detail-grid"><img src="${p.img}" alt="${p.name}"><div><p class="eyebrow">${p.type.toUpperCase()}</p><h2>${p.name}</h2><div class="detail-price">${money(p.price)}</div><div class="detail-bs">${p.bs} · ★ ${p.rating}</div><p class="detail-copy">${p.desc}</p><ul class="detail-list">${p.specs.map(s=>`<li>${s}</li>`).join('')}</ul><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-primary" id="detail-add">Agregar al carrito →</button><a class="btn btn-ghost" href="producto.html?id=${p.id}">Abrir página completa</a></div></div></div>`;$('#detail-add').onclick=()=>addToCart(p.id);$('#product-modal').setAttribute('aria-hidden','false')}
function updateCompareBar(){$('#compare-bar').setAttribute('aria-hidden',state.compare.length?'false':'true');$('#compare-label').textContent=state.compare.length?`${state.compare.length}/3 seleccionados`:'Selecciona hasta 3 productos.'}
function openCompare(){if(state.compare.length<2)return toast('Selecciona al menos 2 productos para comparar');const list=state.compare.map(getProduct);const rows=[['Producto',...list.map(p=>p.name)],['Precio',...list.map(p=>money(p.price))],['Calificación',...list.map(p=>`★ ${p.rating}`)],['Tipo',...list.map(p=>p.type)],['Especificaciones',...list.map(p=>p.specs.slice(0,3).join(' · '))]];$('#compare-table').innerHTML=`<div class="compare-grid">${rows.flatMap((row,i)=>row.map((c,j)=>`<div class="compare-cell ${i===0?'head':''}">${c}</div>`)).join('')}</div>`;$('#compare-modal').setAttribute('aria-hidden','false')}
function closeModal(id){$(id).setAttribute('aria-hidden','true')}
$('#product-grid')?.addEventListener('click',e=>{const card=e.target.closest('.product-card');if(card&&!e.target.closest('button')&&!e.target.closest('a'))openProductModal(card.dataset.id)});
$$('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.filter=btn.dataset.filter;renderProducts()}));
$$('[data-filter-link]').forEach(a=>a.addEventListener('click',()=>{state.filter=a.dataset.filterLink;$$('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.filter===state.filter));setTimeout(renderProducts,0)}));
$$('[data-cart]').forEach(b=>b.addEventListener('click',openCart));$('.close-cart')?.addEventListener('click',closeCart);$('#drawer-overlay')?.addEventListener('click',closeCart);$('#checkout-start')?.addEventListener('click',e=>{e.preventDefault();openCheckout()});
$('#checkout-close')?.addEventListener('click',()=>closeModal('#payment'));$('#search-open')?.addEventListener('click',openSearch);$('#search-close')?.addEventListener('click',closeSearch);$('#search-input')?.addEventListener('input',e=>runSearch(e.target.value));
$('#mobile-open')?.addEventListener('click',()=>$('#mobile-nav').setAttribute('aria-hidden','false'));$('#mobile-close')?.addEventListener('click',()=>$('#mobile-nav').setAttribute('aria-hidden','true'));$$('.mobile-nav a').forEach(a=>a.addEventListener('click',()=>$('#mobile-nav').setAttribute('aria-hidden','true')));
$$('.pay-option').forEach(b=>b.addEventListener('click',()=>{$$('.pay-option').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`Pago seleccionado: ${b.querySelector('b').textContent}`)}));$('#checkout-form')?.addEventListener('submit',e=>{e.preventDefault();toast(`Demo: pago ${$('.pay-option.active b').textContent} preparado`);setTimeout(closeCheckout,800)});
$('#newsletter-form')?.addEventListener('submit',e=>{e.preventDefault();e.target.reset();toast('Listo. Te avisaremos de las próximas ofertas.')});
$('#compare-open')?.addEventListener('click',openCompare);$('#compare-clear')?.addEventListener('click',()=>{state.compare=[];persist();updateCompareBar();renderProducts()});$('#compare-close')?.addEventListener('click',()=>closeModal('#compare-modal'));$('#product-close')?.addEventListener('click',()=>closeModal('#product-modal'));
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));
let tx=innerWidth/2,ty=innerHeight/2,cx=tx,cy=ty;addEventListener('pointermove',e=>{tx=e.clientX;ty=e.clientY});function cursorLoop(){cx+=(tx-cx)*.11;cy+=(ty-cy)*.11;const g=$('.cursor-glow');if(g){g.style.left=cx+'px';g.style.top=cy+'px'}requestAnimationFrame(cursorLoop)}cursorLoop();
$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.12,y=(e.clientY-r.top-r.height/2)*.12;el.style.transform=`translate(${x}px,${y}px) translateY(-2px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
$$('.tilt-card').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateY(${x*6}deg) rotateX(${y*-6}deg) rotate(1deg) translateY(-8px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
let remaining=2*60*60+14*60+36;setInterval(()=>{if(remaining<=0)return;remaining--;const h=String(Math.floor(remaining/3600)).padStart(2,'0'),m=String(Math.floor((remaining%3600)/60)).padStart(2,'0'),s=String(remaining%60).padStart(2,'0');const c=$('#countdown');if(c)c.textContent=`${h} : ${m} : ${s}`},1000);
renderProducts();updateCart();updateCompareBar();
